version: 1
validation: sovereign
default_denom: ulbt
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000ulbt
- name: bob
  coins:
  - 10000token
  - 100000000ulbt
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5token
  - 100000ulbt
validators:
- name: alice
  bonded: 100000000ulbt
- name: validator1
  bonded: 200000000ulbt
- name: validator2
  bonded: 100000000ulbt

# Ensure transfer module params exist so exports succeed.
genesis:
  app_state:
    transfer:
      params:
        send_enabled: true
        receive_enabled: true

build:
  proto:
    openapi: false
    swagger: false
  app:
    minimum_gas_prices: 0.025ulbt
